### ISSUE TITLE
Improper display of long indented hyperlinks in text files with soft wrap

### ISSUE THREAD

**Issue by Bennettson** [atom/language-hyperlink#16]
### Prerequisites

* [X] All done! Including "safe mode" and "factory settings".

### Description:

Long indented hyperlinks produce these ugly ugly lines when soft wrap is enabled in atom:

![atom_lorem_link_circled](https://cloud.githubusercontent.com/assets/19208670/23333215/175be1b2-fb88-11e6-8d6f-cb271c7ed9c8.png)

How do I get rid of these lines? The blank spaces should not be underlined since they're not part of the hyperlink.

### Steps to Reproduce:

1. Optional: Reset to factory defaults with `mv ~/.atom ~/.atom-backup` under linux.
2. Copy-paste a long hyperlink in a .txt file.
3. Indent it with a few tabs.
4. Enable Soft Wrap with: Edit > Toggle Soft Wrap.

I get the ugly lines 100% of the time on two different computers.

### Configuration:

`atom --version`:
Atom: 1.14.3
Electron: 1.3.13
Chrome: 52.0.2743.82
Node: 6.5.0
`apm --version`:
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 3.6.0
git 2.11.1

Please let me know if you need more info.

And thank you __so very much__ for the work you're doing!! :D

**Comment by simurai** [comment]
@Bennettson What's the syntax theme you're using? I can't reproduce with any theme I tried.

For example One Dark Syntax should look like this:

![screen shot 2017-02-28 at 11 43 57 am](https://cloud.githubusercontent.com/assets/378023/23389450/5db9346e-fdab-11e6-960e-e93a54da299c.png)

**Comment by Bennettson** [comment]
I am using the One Dark Syntax as well. I tried all the syntax themes but the issue remained.

I noticed that you have the "Indent Guide" enabled. So I tried that: `Settings > Editor > Show Indent Guide`

Here is the result with the __Indent Guide disabled__:

![no_indent_guide](https://cloud.githubusercontent.com/assets/19208670/23402080/640f1866-fdaa-11e6-99b7-27fd6bc251ea.png)

And here is the result with the __Indent Guide enabled__ (no problem there):

![indent_guide](https://cloud.githubusercontent.com/assets/19208670/23402091/6c25b172-fdaa-11e6-8d50-7897a22b8ac4.png)

Is this of any help?

**Comment by simurai** [comment]
> @Bennettson Indent Guide disabled

Yes, that's it. 👌 

> @50Wliu where would you say this issue belongs?

Hmm.. good question. Seems that when disabling the indent guides, the indentation is done with whitespace characters:

![screen shot 2017-02-28 at 9 15 29 pm](https://cloud.githubusercontent.com/assets/378023/23405122/15ec9db4-fdfc-11e6-9ac2-18f8d52acb7d.png)

Could the indentation always be done with `span`s? Like 

```html
<span class="indent">  </span>
```

Probably bad for performance with lots more elements? /cc @atom/core

**Comment by lee-dohm** [comment]
Great catch @Bennettson! Since this isn't a flaw in the language-hyperlink package itself and more of a problem with rendering, would you mind reopening this issue on https://github.com/atom/atom? When you do, please @-mention @AndreaGriffiths11 on the issue so that we can get it tracked.

**Comment by Bennettson** [comment]
Closed! This issue now lives at https://github.com/atom/atom/issues/13901.
