### ISSUE TITLE
Links with underscores not fully highlighted

### ISSUE THREAD

**Issue by peterjc** [atom/language-hyperlink#7]
(Apologies if I have reported this in the wrong part of the Atom family, please redirect me as necessary)

Steps to reproduce:

1. Download and run Atom 1.2.4 (for Mac in case the following makes any difference), which includes language-hyperlink v0.15.0
2. Go to menu: File, New File,
3. Copy and paste the following into the new file:

Here is a short URL with no underscores http://www.example.org/page.html and here is another URL http://www.example.org/page_two.html which has an internal underscore.

4. Notice default is plain text and has no coloring.
5. Click the bottom right to change from "plain text" to "GitHub Markdown"
6. Notice that ``http://www.example.org/page.html`` is now purple (good)
7. Notice that only ``http://www.example.org/page`` is purple, and not ``_two.html`` (bad)

My guess is this is an unfortunate side effect from https://github.com/atom/language-hyperlink/commit/d457a73a2b1d806e76becd0442543d86e81618d7

This was initially raised as https://github.com/Lukasa/language-restructuredtext/issues/27 within RST files, but that uses the ``url`` definition which I believe comes from this package?

**Comment by lee-dohm** [comment]
Confirmed using Atom v1.4.0-dev-f159e81 on Mac OS X 10.11.1.

**Comment by boone** [comment]
Here's a possible fix: #8.

**Comment by kevinsawicki** [comment]
Fixed by #8
